function(sunshine_validate_ds5_package component)
    if(NOT EXISTS "${component}/component.json")
        message(FATAL_ERROR "DualSense component.json is missing: ${component}")
    endif()
    file(READ "${component}/component.json" _manifest)
    string(JSON _protocol GET "${_manifest}" protocol)
    string(JSON _installer GET "${_manifest}" installer_driver_setup)
    string(JSON _version GET "${_manifest}" hidmaestro_version)
    string(JSON _core GET "${_manifest}" files HIDMaestro.Core.dll)
    string(JSON _sidecar GET "${_manifest}" sidecar_file)
    string(JSON _sidecar_hash GET "${_manifest}" sidecar_sha256)
    string(JSON _sidecar_file_hash GET "${_manifest}" files Sunshine.Ds5Sidecar.exe)
    if(NOT _protocol EQUAL 1 OR NOT _installer EQUAL 1 OR NOT _version STREQUAL "1.6.2.0"
        OR NOT _core STREQUAL "df59cd5b6031311f03031c32b794901fc1f45503410f4f6ad55eaa854cee8746"
        OR NOT _sidecar STREQUAL "Sunshine.Ds5Sidecar.exe"
        OR NOT _sidecar_hash STREQUAL _sidecar_file_hash)
        message(FATAL_ERROR "DualSense component is not the supported pinned runtime/manifest.")
    endif()
    string(JSON _count LENGTH "${_manifest}" files)
    math(EXPR _last "${_count} - 1")
    set(_expected component.json)
    foreach(_index RANGE 0 ${_last})
        string(JSON _name MEMBER "${_manifest}" files ${_index})
        if(_name MATCHES "[/\\\\:]" OR _name MATCHES "^[.]" OR _name STREQUAL "component.json")
            message(FATAL_ERROR "Unsafe DualSense manifest filename: ${_name}")
        endif()
        if(IS_DIRECTORY "${component}/${_name}" OR IS_SYMLINK "${component}/${_name}")
            message(FATAL_ERROR "DualSense payload must contain regular flat files: ${_name}")
        endif()
        string(JSON _expected_hash GET "${_manifest}" files "${_name}")
        file(SHA256 "${component}/${_name}" _actual_hash)
        if(NOT _actual_hash STREQUAL _expected_hash)
            message(FATAL_ERROR "DualSense payload checksum mismatch: ${_name}")
        endif()
        list(APPEND _expected "${_name}")
    endforeach()
    file(GLOB _actual RELATIVE "${component}" "${component}/*")
    list(SORT _expected)
    list(SORT _actual)
    if(NOT "${_expected}" STREQUAL "${_actual}")
        message(FATAL_ERROR "DualSense component contains unmanifested files or directories.")
    endif()
endfunction()
