#!/usr/bin/env python3
"""Generate C++ and HLSL declarations from the canonical Scene Controller ABI."""

from __future__ import annotations

import argparse
import re
import struct
import sys
from pathlib import Path
from typing import Any

from scene_controller_contract import CONTRACT, compute_ordered_abi_hash, validate_contract


ROOT = Path(__file__).resolve().parents[2]
CPP_TARGET = ROOT / "src" / "generated" / "sbs_scene_controller_contract.h"
HLSL_TARGET = (
    ROOT
    / "src_assets"
    / "windows"
    / "assets"
    / "shaders"
    / "directx"
    / "include"
    / "sbs_scene_controller_contract.generated.hlsl"
)

_COMPONENTS = ("x", "y", "z", "w")
_DYNAMIC_SHAPE_VALUES = {"Hd": -1, "Wd": -2}


def _identifier(value: str) -> str:
    result = re.sub(r"[^a-zA-Z0-9_]", "_", value)
    if not result or result[0].isdigit():
        raise ValueError(f"cannot turn {value!r} into an identifier")
    return result


def _upper_identifier(value: str) -> str:
    return _identifier(value).upper()


def _float_literal(value: float | int) -> str:
    numeric = float(value)
    if numeric == 0.0:
        return "0.0f"
    if numeric.is_integer():
        return f"{int(numeric)}.0f"
    return f"{numeric:.9g}f"


def _initial_word_bits(field: dict[str, Any]) -> int:
    initial = field["initial"]
    if field["gpu_encoding"] == "uint_bits":
        return int(initial) & 0xFFFFFFFF
    return struct.unpack("<I", struct.pack("<f", float(initial)))[0]


def _shape_values(shape: list[int | str]) -> tuple[int, int, int, int]:
    values = [
        int(value) if isinstance(value, int) else _DYNAMIC_SHAPE_VALUES[value]
        for value in shape
    ]
    values.extend([1] * (4 - len(values)))
    return tuple(values)  # type: ignore[return-value]


def _render_cpp_indexed_enum(
    lines: list[str],
    enum_name: str,
    entries: list[dict[str, Any]],
) -> None:
    lines.append(f"  enum class {enum_name}_e : std::size_t {{")
    lines.extend(
        f"    {_identifier(entry['name'])} = {entry['index']}u,"
        for entry in entries
    )
    lines.extend([f"    count = {len(entries)}u,", "  };", ""])


def _render_cpp_name_array(
    lines: list[str],
    name: str,
    entries: list[dict[str, Any]],
) -> None:
    lines.append(
        f"  inline constexpr std::array<std::string_view, {len(entries)}> {name} {{{{"
    )
    lines.extend(f'    "{entry["name"]}",' for entry in entries)
    lines.extend(["  }};", ""])


def render_cpp(contract: dict[str, Any]) -> str:
    validate_contract(contract)
    dimensions = {
        dimension["name"]: dimension["value"] for dimension in contract["dimensions"]
    }
    hash_value = compute_ordered_abi_hash(contract)
    hash_words = [
        int(hash_value[offset : offset + 8], 16)
        for offset in range(0, len(hash_value), 8)
    ]
    lines = [
        "// Generated by tools/sbsbench/generate_scene_controller_contract.py.",
        "// Edit tools/sbsbench/contracts/sbs-scene-controller-v1.json instead.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace sbs_scene_controller {",
        f"  inline constexpr std::uint32_t schema_version = {contract['schema']}u;",
        f'  inline constexpr std::string_view rule_revision = "{contract["rule_revision"]}";',
        f'  inline constexpr std::string_view ordered_abi_hash = "{hash_value}";',
        "  inline constexpr std::array<std::uint32_t, 8> ordered_abi_hash_words {{",
    ]
    lines.extend(f"    0x{word:08x}u," for word in hash_words)
    lines.extend(["  }};", ""])
    for name, value in dimensions.items():
        cpp_type = "std::size_t"
        lines.append(f"  inline constexpr {cpp_type} {_identifier(name)} = {value}u;")
    lines.extend(
        [
            "  inline constexpr std::size_t rule_state_vector_count = "
            "rule_state_word_count / 4u;",
            "  inline constexpr std::int32_t dynamic_hd = -1;",
            "  inline constexpr std::int32_t dynamic_wd = -2;",
            "",
            "  enum class gpu_encoding_e {",
            "    float_value,",
            "    uint_bits,",
            "    uint_valued_float,",
            "  };",
            "",
            "  struct tensor_descriptor_t {",
            "    std::size_t index;",
            "    std::string_view name;",
            "    std::string_view type;",
            "    std::uint32_t rank;",
            "    std::array<std::int32_t, 4> shape;",
            "  };",
            "",
        ]
    )
    for section, enum_name, array_name in (
        ("inputs", "input_tensor", "input_tensors"),
        ("outputs", "output_tensor", "output_tensors"),
    ):
        entries = contract[section]
        _render_cpp_indexed_enum(lines, enum_name, entries)
        lines.append(
            f"  inline constexpr std::array<tensor_descriptor_t, {len(entries)}> "
            f"{array_name} {{{{"
        )
        for entry in entries:
            shape = _shape_values(entry["shape"])
            shape_text = ", ".join(str(value) for value in shape)
            lines.append(
                f'    {{{entry["index"]}u, "{entry["name"]}", "{entry["type"]}", '
                f'{len(entry["shape"])}u, {{{{{shape_text}}}}}}},'
            )
        lines.extend(["  }};", ""])

    indexed_sections = (
        ("analysis_grid", "analysis_grid_channel", "analysis_grid_names"),
        ("layout_history", "layout_history_channel", "layout_history_names"),
        ("depth_history", "depth_history_channel", "depth_history_names"),
        ("meta", "meta_word", "meta_names"),
        ("dense_out", "dense_out_channel", "dense_out_names"),
        ("global_out", "global_out_word", "global_out_names"),
    )
    for section, enum_name, array_name in indexed_sections:
        _render_cpp_indexed_enum(lines, enum_name, contract[section])
        _render_cpp_name_array(lines, array_name, contract[section])

    rule_state = contract["rule_state"]
    _render_cpp_indexed_enum(lines, "rule_state_word", rule_state)
    lines.extend(
        [
            "  constexpr std::size_t index(const rule_state_word_e word) {",
            "    return static_cast<std::size_t>(word);",
            "  }",
            "",
            "  struct rule_state_field_descriptor_t {",
            "    rule_state_word_e word;",
            "    std::string_view name;",
            "    std::string_view json_type;",
            "    gpu_encoding_e gpu_encoding;",
            "    float initial_value;",
            "    bool required_zero;",
            "  };",
            "",
            f"  inline constexpr std::array<rule_state_field_descriptor_t, "
            f"{len(rule_state)}> rule_state_fields {{{{",
        ]
    )
    encoding_names = {
        "float": "float_value",
        "uint_bits": "uint_bits",
        "uint_valued_float": "uint_valued_float",
    }
    for field in rule_state:
        lines.append(
            "    {rule_state_word_e::%s, \"%s\", \"%s\", gpu_encoding_e::%s, %s, %s},"
            % (
                _identifier(field["name"]),
                field["name"],
                field["type"],
                encoding_names[field["gpu_encoding"]],
                _float_literal(field["initial"]),
                "true" if field.get("required_zero") else "false",
            )
        )
    lines.extend(
        [
            "  }};",
            "",
            "  inline constexpr std::array<float, rule_state_word_count> initial_values {{",
        ]
    )
    lines.extend(f"    {_float_literal(field['initial'])}," for field in rule_state)
    lines.extend(
        [
            "  }};",
            "",
            "  inline constexpr std::array<std::uint32_t, rule_state_word_count> "
            "initial_word_bits {{",
        ]
    )
    lines.extend(f"    0x{_initial_word_bits(field):08x}u," for field in rule_state)
    lines.extend(["  }};", ""])

    for enum_name, values in contract["enums"].items():
        lines.append(f"  enum class {_identifier(enum_name)}_e : std::uint32_t {{")
        lines.extend(
            f"    {_identifier(name)} = {value}u," for name, value in values.items()
        )
        lines.extend(["  };", ""])

    lines.extend(
        [
            "  struct named_bit_t {",
            "    std::string_view name;",
            "    std::uint32_t bit;",
            "    std::uint32_t mask;",
            "  };",
            "",
        ]
    )
    for flag_name, bits in contract["flag_bits"].items():
        for name, bit in bits.items():
            lines.append(
                f"  inline constexpr std::uint32_t {_identifier(flag_name)}_"
                f"{_identifier(name)} = 1u << {bit}u;"
            )
        lines.append(
            f"  inline constexpr std::array<named_bit_t, {len(bits)}> "
            f"{_identifier(flag_name)}_bits {{{{"
        )
        lines.extend(
            f'    {{"{name}", {bit}u, {_identifier(flag_name)}_{_identifier(name)}}},'
            for name, bit in bits.items()
        )
        lines.extend(["  }};", ""])

    lines.extend(
        [
            "  constexpr bool rule_state_layout_matches_indices() {",
            "    for (std::size_t position = 0; position < rule_state_fields.size(); ++position) {",
            "      if (index(rule_state_fields[position].word) != position) {",
            "        return false;",
            "      }",
            "    }",
            "    return true;",
            "  }",
            "",
            "  static_assert(rule_state_word_count % 4u == 0u);",
            "  static_assert(rule_state_vector_count == 16u);",
            "  static_assert(rule_state_layout_matches_indices());",
            f"  static_assert(analysis_grid_names.size() == analysis_grid_channel_count);",
            f"  static_assert(layout_history_names.size() == layout_history_channel_count);",
            f"  static_assert(depth_history_names.size() == depth_history_channel_count);",
            f"  static_assert(meta_names.size() == meta_word_count);",
            f"  static_assert(dense_out_names.size() == dense_out_channel_count);",
            f"  static_assert(global_out_names.size() == global_out_word_count);",
            "}  // namespace sbs_scene_controller",
            "",
        ]
    )
    return "\n".join(lines)


def _render_hlsl_index_macros(
    lines: list[str],
    prefix: str,
    entries: list[dict[str, Any]],
) -> None:
    for entry in entries:
        lines.append(
            f"#define SBS_SCENE_{prefix}_{_upper_identifier(entry['name'])} "
            f"{entry['index']}u"
        )
    lines.append("")


def render_hlsl(contract: dict[str, Any]) -> str:
    validate_contract(contract)
    dimensions = {
        dimension["name"]: dimension["value"] for dimension in contract["dimensions"]
    }
    hash_value = compute_ordered_abi_hash(contract)
    hash_words = [
        int(hash_value[offset : offset + 8], 16)
        for offset in range(0, len(hash_value), 8)
    ]
    lines = [
        "// Generated by tools/sbsbench/generate_scene_controller_contract.py.",
        "// Edit tools/sbsbench/contracts/sbs-scene-controller-v1.json instead.",
        "#ifndef SBS_SCENE_CONTROLLER_CONTRACT_GENERATED_HLSL",
        "#define SBS_SCENE_CONTROLLER_CONTRACT_GENERATED_HLSL",
        "",
        f"#define SBS_SCENE_SCHEMA_VERSION {contract['schema']}u",
    ]
    lines.extend(
        f"#define SBS_SCENE_ORDERED_ABI_HASH_WORD_{index} 0x{word:08x}u"
        for index, word in enumerate(hash_words)
    )
    lines.append("")
    for name, value in dimensions.items():
        lines.append(f"#define SBS_SCENE_{_upper_identifier(name)} {value}u")
    lines.append(
        "#define SBS_SCENE_RULE_STATE_VECTOR_COUNT "
        "(SBS_SCENE_RULE_STATE_WORD_COUNT / 4u)"
    )
    lines.append("")

    _render_hlsl_index_macros(lines, "INPUT", contract["inputs"])
    _render_hlsl_index_macros(lines, "OUTPUT", contract["outputs"])
    for section, prefix in (
        ("analysis_grid", "ANALYSIS_GRID"),
        ("layout_history", "LAYOUT_HISTORY"),
        ("depth_history", "DEPTH_HISTORY"),
        ("meta", "META"),
        ("dense_out", "DENSE_OUT"),
        ("global_out", "GLOBAL_OUT"),
    ):
        _render_hlsl_index_macros(lines, prefix, contract[section])

    rule_state = contract["rule_state"]
    for field in rule_state:
        upper = _upper_identifier(field["name"])
        vector_index = int(field["index"]) // 4
        component = _COMPONENTS[int(field["index"]) % 4]
        lines.extend(
            [
                f"#define SBS_SCENE_RULE_STATE_WORD_{upper} {field['index']}u",
                f"#define SBS_SCENE_RULE_STATE_VECTOR_{upper} {vector_index}u",
                f"#define SBS_SCENE_RULE_STATE_{upper}(value) ((value).{component})",
            ]
        )
        if field["gpu_encoding"] == "uint_bits":
            lines.append(
                f"#define SBS_SCENE_RULE_STATE_{upper}_U32(value) "
                f"(asuint((value).{component}))"
            )
    lines.append("")

    for vector_index in range(len(rule_state) // 4):
        fields = rule_state[vector_index * 4 : vector_index * 4 + 4]
        values = ", ".join(_float_literal(field["initial"]) for field in fields)
        lines.append(
            f"#define SBS_SCENE_RULE_STATE_INITIAL_VECTOR_{vector_index} "
            f"float4({values})"
        )
    lines.extend(
        [
            "",
            "float4 SbsSceneRuleStateInitialVector(uint vector_index) {",
            "  switch (vector_index) {",
        ]
    )
    lines.extend(
        f"    case {index}u: return SBS_SCENE_RULE_STATE_INITIAL_VECTOR_{index};"
        for index in range(len(rule_state) // 4)
    )
    lines.extend(["    default: return 0.0f;", "  }", "}", ""])

    for enum_name, values in contract["enums"].items():
        prefix = _upper_identifier(enum_name)
        lines.extend(
            f"#define SBS_SCENE_{prefix}_{_upper_identifier(name)} {value}u"
            for name, value in values.items()
        )
        lines.append("")
    for flag_name, bits in contract["flag_bits"].items():
        prefix = _upper_identifier(flag_name)
        lines.extend(
            f"#define SBS_SCENE_{prefix}_{_upper_identifier(name)} (1u << {bit}u)"
            for name, bit in bits.items()
        )
        lines.append("")

    lines.extend(["#endif", ""])
    return "\n".join(lines)


def _write_or_check(path: Path, expected: str, check: bool) -> bool:
    if check:
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            print(f"missing generated scene-controller contract: {path}", file=sys.stderr)
            return False
        if actual != expected:
            print(f"stale generated scene-controller contract: {path}", file=sys.stderr)
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if committed generated files differ from the canonical manifest",
    )
    args = parser.parse_args()
    valid = _write_or_check(CPP_TARGET, render_cpp(CONTRACT), args.check)
    valid &= _write_or_check(HLSL_TARGET, render_hlsl(CONTRACT), args.check)
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
