#!/usr/bin/env python3
"""Generate native and HLSL adaptive-state declarations from the canonical manifest."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
MANIFEST = (
    ROOT / "tools" / "sbsbench" / "contracts" / "sbs-adaptive-state-v4.json"
)
CPP_TARGET = ROOT / "src" / "generated" / "sbs_adaptive_state_contract.h"
HLSL_TARGET = (
    ROOT
    / "src_assets"
    / "windows"
    / "assets"
    / "shaders"
    / "directx"
    / "include"
    / "sbs_adaptive_state_contract.generated.hlsl"
)


def _identifier(value: str) -> str:
    identifier = re.sub(r"[^a-zA-Z0-9_]", "_", value)
    if not identifier or identifier[0].isdigit():
        raise ValueError(f"cannot turn {value!r} into an identifier")
    return identifier


def _upper_identifier(value: str) -> str:
    return _identifier(value).upper()


def _float_literal(value: float | int) -> str:
    numeric = float(value)
    if numeric.is_integer():
        return f"{int(numeric)}.0f"
    return f"{numeric:.9g}f"


def _load() -> dict[str, Any]:
    with MANIFEST.open(encoding="utf-8") as stream:
        contract = json.load(stream)
    fields = contract["fields"]
    if [field["index"] for field in fields] != list(range(len(fields))):
        raise ValueError("manifest fields must be ordered by contiguous index")
    if len(fields) % 4:
        raise ValueError("manifest field count must be divisible by four")
    return contract


def _render_string_array(name: str, values: list[str]) -> list[str]:
    lines = [
        f"  inline constexpr std::array<std::string_view, {len(values)}> {name} {{{{",
    ]
    lines.extend(f'    "{value}",' for value in values)
    lines.append("  }};")
    return lines


def render_cpp(contract: dict[str, Any]) -> str:
    fields = contract["fields"]
    cut_bits = contract["cut_flag_bits"]
    analysis_bits = contract["analysis_flag_bits"]
    lines = [
        "// Generated by tools/sbsbench/generate_adaptive_state_contract.py.",
        "// Edit tools/sbsbench/contracts/sbs-adaptive-state-v4.json instead.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace sbs_adaptive_state {",
        f"  inline constexpr std::uint32_t schema_version = {contract['schema']}u;",
        f'  inline constexpr std::string_view source = "{contract["source"]}";',
        f'  inline constexpr std::string_view capture = "{contract["capture"]}";',
        f"  inline constexpr std::size_t render_prefix_word_count = "
        f"{contract['render_prefix_words']}u;",
        "",
        "  enum class gpu_encoding_e {",
        "    float_value,",
        "    uint_bits,",
        "    uint_valued_float,",
        "  };",
        "",
        "  enum class word_e : std::size_t {",
    ]
    lines.extend(
        f"    {_identifier(field['name'])} = {field['index']}u,"
        for field in fields
    )
    lines.extend([
        f"    count = {len(fields)}u,",
        "  };",
        "",
        "  constexpr std::size_t index(const word_e word) {",
        "    return static_cast<std::size_t>(word);",
        "  }",
        "",
        "  inline constexpr std::size_t word_count = index(word_e::count);",
        "  inline constexpr std::size_t vector_count = word_count / 4u;",
        "  using words_t = std::array<std::uint32_t, word_count>;",
        "",
        "  struct field_descriptor_t {",
        "    word_e word;",
        "    std::string_view name;",
        "    std::string_view json_type;",
        "    gpu_encoding_e gpu_encoding;",
        "    float initial_value;",
        "  };",
        "",
        f"  inline constexpr std::array<field_descriptor_t, {len(fields)}> fields {{{{",
    ])
    encoding = {
        "float": "float_value",
        "uint_bits": "uint_bits",
        "uint_valued_float": "uint_valued_float",
    }
    lines.extend(
        "    {word_e::%s, \"%s\", \"%s\", gpu_encoding_e::%s, %s},"
        % (
            _identifier(field["name"]),
            field["name"],
            field["type"],
            encoding[field["gpu_encoding"]],
            _float_literal(field["initial"]),
        )
        for field in fields
    )
    lines.extend([
        "  }};",
        "",
        "  inline constexpr std::array<float, word_count> initial_values {{",
    ])
    lines.extend(
        f"    {_float_literal(field['initial'])}," for field in fields
    )
    lines.extend([
        "  }};",
        "",
        "  constexpr bool field_layout_matches_indices() {",
        "    for (std::size_t position = 0; position < fields.size(); ++position) {",
        "      if (index(fields[position].word) != position) {",
        "        return false;",
        "      }",
        "    }",
        "    return true;",
        "  }",
        "",
        "  static_assert(word_count % 4u == 0u);",
        "  static_assert(render_prefix_word_count % 4u == 0u);",
        "  static_assert(render_prefix_word_count <= word_count);",
        "  static_assert(field_layout_matches_indices());",
        "",
        "  struct named_bit_t {",
        "    std::string_view name;",
        "    std::uint32_t bit;",
        "    std::uint32_t mask;",
        "  };",
        "",
    ])
    for name, bit in cut_bits.items():
        lines.append(
            f"  inline constexpr std::uint32_t cut_flag_{_identifier(name)} = "
            f"1u << {bit}u;"
        )
    lines.extend([
        f"  inline constexpr std::uint32_t known_cut_flag_mask = "
        f"{sum(1 << int(bit) for bit in cut_bits.values())}u;",
        f"  inline constexpr std::array<named_bit_t, {len(cut_bits)}> cut_flag_bits {{{{",
    ])
    lines.extend(
        f'    {{"{name}", {bit}u, cut_flag_{_identifier(name)}}},'
        for name, bit in cut_bits.items()
    )
    lines.extend(["  }};", ""])
    for name, bit in analysis_bits.items():
        lines.append(
            f"  inline constexpr std::uint32_t analysis_flag_{_identifier(name)} = "
            f"1u << {bit}u;"
        )
    lines.extend([
        f"  inline constexpr std::uint32_t known_analysis_flag_mask = "
        f"{sum(1 << int(bit) for bit in analysis_bits.values())}u;",
        f"  inline constexpr std::array<named_bit_t, {len(analysis_bits)}> "
        "analysis_flag_bits {{",
    ])
    lines.extend(
        f'    {{"{name}", {bit}u, analysis_flag_{_identifier(name)}}},'
        for name, bit in analysis_bits.items()
    )
    lines.extend(["  }};", ""])
    lines.extend(_render_string_array("header_keys", contract["header_keys"]))
    lines.append("")
    lines.extend(_render_string_array("config_keys", contract["config_keys"]))
    lines.append("")
    lines.extend(_render_string_array("frame_keys", contract["frame_keys"]))
    lines.extend(["}  // namespace sbs_adaptive_state", ""])
    return "\n".join(lines)


def render_hlsl(contract: dict[str, Any]) -> str:
    fields = contract["fields"]
    component_names = ("x", "y", "z", "w")
    lines = [
        "// Generated by tools/sbsbench/generate_adaptive_state_contract.py.",
        "// Edit tools/sbsbench/contracts/sbs-adaptive-state-v4.json instead.",
        "#ifndef SBS_ADAPTIVE_STATE_CONTRACT_GENERATED_HLSL",
        "#define SBS_ADAPTIVE_STATE_CONTRACT_GENERATED_HLSL",
        "",
        f"#define SBS_ADAPTIVE_STATE_SCHEMA {contract['schema']}u",
        f"#define SBS_ADAPTIVE_STATE_WORD_COUNT {len(fields)}u",
        f"#define SBS_ADAPTIVE_STATE_VECTOR_COUNT {len(fields) // 4}u",
        f"#define SBS_ADAPTIVE_STATE_RENDER_PREFIX_WORD_COUNT "
        f"{contract['render_prefix_words']}u",
        "",
    ]
    for field in fields:
        upper = _upper_identifier(field["name"])
        vector = int(field["index"]) // 4
        component = component_names[int(field["index"]) % 4]
        lines.extend([
            f"#define SBS_STATE_WORD_{upper} {field['index']}u",
            f"#define SBS_STATE_VECTOR_{upper} {vector}u",
            f"#define SBS_STATE_{upper}(value) ((value).{component})",
        ])
    lines.append("")
    for name, bit in contract["cut_flag_bits"].items():
        lines.append(f"#define CUT_FLAG_{_upper_identifier(name)} {1 << int(bit)}u")
    lines.append("")
    for name, bit in contract["analysis_flag_bits"].items():
        lines.append(
            f"#define ANALYSIS_FLAG_{_upper_identifier(name)} {1 << int(bit)}u"
        )
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def _write_or_check(path: Path, expected: str, check: bool) -> bool:
    if check:
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            print(f"missing generated contract: {path}", file=sys.stderr)
            return False
        if actual != expected:
            print(f"stale generated contract: {path}", file=sys.stderr)
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if committed generated files differ from the manifest",
    )
    args = parser.parse_args()
    contract = _load()
    valid = _write_or_check(CPP_TARGET, render_cpp(contract), args.check)
    valid &= _write_or_check(HLSL_TARGET, render_hlsl(contract), args.check)
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
