// Generated by tools/sbsbench/generate_depth_coordinate_v2_contract.py.
// Edit tools/sbsbench/contracts/depth-coordinate-v2-v1.json instead.
#ifndef DEPTH_COORDINATE_V2_CONTRACT_GENERATED_HLSL
#define DEPTH_COORDINATE_V2_CONTRACT_GENERATED_HLSL

#define V2_CONTRACT_SCHEMA 46u
#define V2_CONTRACT_TAG 0xD18FF0F3u
#define V2_SHADOW_STATE_WORD_COUNT 12u
#define V2_SHADOW_STATE_VECTOR_COUNT 3u
#define V2_SUBTITLE_OCR_CONTRACT_SCHEMA 6u
#define V2_OCR_INPUT_N 1u
#define V2_OCR_INPUT_C 3u
#define V2_OCR_INPUT_HEIGHT 160u
#define V2_OCR_INPUT_WIDTH 960u
#define V2_OCR_OUTPUT_N 1u
#define V2_OCR_OUTPUT_C 1u
#define V2_OCR_OUTPUT_HEIGHT 160u
#define V2_OCR_OUTPUT_WIDTH 960u
#define V2_OCR_IMAGENET_MEAN_B 0.485f
#define V2_OCR_IMAGENET_MEAN_G 0.456f
#define V2_OCR_IMAGENET_MEAN_R 0.406f
#define V2_OCR_IMAGENET_STD_B 0.229f
#define V2_OCR_IMAGENET_STD_G 0.224f
#define V2_OCR_IMAGENET_STD_R 0.225f
#define V2_OCR_RECORD_SCHEMA 3u
#define V2_OCR_RECORD_TAG 0x3852434Fu
#define V2_OCR_RECORD_WORD_COUNT 208u
#define V2_OCR_RECORD_HEADER_WORD_COUNT 16u
#define V2_OCR_BOX_WORD_COUNT 8u
#define V2_OCR_BOX_FLAG_RIBBON 1u
#define V2_OCR_BOX_KNOWN_FLAGS 1u
#define V2_OCR_RAW_BOX_OFFSET 16u
#define V2_OCR_RAW_BOX_CAPACITY 16u
#define V2_OCR_FINAL_BOX_OFFSET 144u
#define V2_OCR_FINAL_BOX_CAPACITY 8u
#define V2_MODEL_CALIBRATED_SHAPE_COUNT 6u
#define V2_MODEL_CALIBRATED_SHAPE_WIDTH_0 770u
#define V2_MODEL_CALIBRATED_SHAPE_HEIGHT_0 434u
#define V2_MODEL_CALIBRATED_SHAPE_WIDTH_1 1022u
#define V2_MODEL_CALIBRATED_SHAPE_HEIGHT_1 434u
#define V2_MODEL_CALIBRATED_SHAPE_WIDTH_2 1036u
#define V2_MODEL_CALIBRATED_SHAPE_HEIGHT_2 434u
#define V2_MODEL_CALIBRATED_SHAPE_WIDTH_3 434u
#define V2_MODEL_CALIBRATED_SHAPE_HEIGHT_3 770u
#define V2_MODEL_CALIBRATED_SHAPE_WIDTH_4 434u
#define V2_MODEL_CALIBRATED_SHAPE_HEIGHT_4 1022u
#define V2_MODEL_CALIBRATED_SHAPE_WIDTH_5 434u
#define V2_MODEL_CALIBRATED_SHAPE_HEIGHT_5 1036u
#define V2_OCR_SAFE_ROW_TOP 24u
#define V2_OCR_SAFE_ROW_BOTTOM 155u
#define V2_OCR_CROP_ASPECT_WIDTH 6u
#define V2_OCR_CROP_ASPECT_HEIGHT 1u
#define V2_OCR_TEXT_JOIN_GAP_CELLS 4u
#define V2_OCR_RIBBON_JOIN_GAP_CELLS 12u
#define V2_OCR_RIBBON_STRUCTURAL_GAP_MIN_CELLS 3u
#define V2_OCR_RIBBON_MIN_STRUCTURAL_GAPS 3u
#define V2_OCR_RIBBON_MIN_WIDTH_NUMERATOR 1u
#define V2_OCR_RIBBON_MIN_WIDTH_DENOMINATOR 2u
#define V2_OCR_RIBBON_BOTTOM_TOLERANCE_PIXELS 2u
#define V2_OCR_RIBBON_COVER_PAD_LIMIT 8u
#define V2_SUBTITLE_LOCATOR_MAX_WIDTH_NUMERATOR 9u
#define V2_SUBTITLE_LOCATOR_MAX_WIDTH_DENOMINATOR 10u
#define V2_SUBTITLE_LOCATOR_STATE_SCHEMA 9u
#define V2_SUBTITLE_LOCATOR_STATE_TAG 0x39524C53u
#define V2_SUBTITLE_LOCATOR_STATE_WORD_COUNT 80u
#define V2_SUBTITLE_LOCATOR_HEADER_WORD_COUNT 32u
#define V2_SUBTITLE_LOCATOR_RECTANGLE_CAPACITY 4u
#define V2_SUBTITLE_LOCATOR_OWNER_OFFSET 32u
#define V2_SUBTITLE_LOCATOR_PENDING_OFFSET 48u
#define V2_SUBTITLE_LOCATOR_CURRENT_OFFSET 64u
#define V2_SUBTITLE_LOCATOR_KIND_WORD 31u
#define V2_SUBTITLE_LOCATOR_OWNER_KIND_SHIFT 0u
#define V2_SUBTITLE_LOCATOR_PENDING_KIND_SHIFT 4u
#define V2_SUBTITLE_LOCATOR_CURRENT_KIND_SHIFT 8u
#define V2_SUBTITLE_LOCATOR_KIND_MASK 15u
#define V2_DIRECT_CONTAINER_LIMIT 0.04f
#define V2_MAX_VERTICAL_SHEAR 2.0f
#define V2_VERTICAL_MAJORANT_SHARE 0.75f
#define V2_CONVERGENCE_CURVE_DEFAULT 0.0f
static const float v2_max_vertical_shear = V2_MAX_VERTICAL_SHEAR;
static const float v2_vertical_majorant_share = V2_VERTICAL_MAJORANT_SHARE;

bool V2SubtitleOcrFieldIsCalibrated(uint field_width, uint field_height) {
    return (field_width == V2_MODEL_CALIBRATED_SHAPE_WIDTH_0 && field_height == V2_MODEL_CALIBRATED_SHAPE_HEIGHT_0) ||
           (field_width == V2_MODEL_CALIBRATED_SHAPE_WIDTH_1 && field_height == V2_MODEL_CALIBRATED_SHAPE_HEIGHT_1) ||
           (field_width == V2_MODEL_CALIBRATED_SHAPE_WIDTH_2 && field_height == V2_MODEL_CALIBRATED_SHAPE_HEIGHT_2) ||
           (field_width == V2_MODEL_CALIBRATED_SHAPE_WIDTH_3 && field_height == V2_MODEL_CALIBRATED_SHAPE_HEIGHT_3) ||
           (field_width == V2_MODEL_CALIBRATED_SHAPE_WIDTH_4 && field_height == V2_MODEL_CALIBRATED_SHAPE_HEIGHT_4) ||
           (field_width == V2_MODEL_CALIBRATED_SHAPE_WIDTH_5 && field_height == V2_MODEL_CALIBRATED_SHAPE_HEIGHT_5);
}

// Exact ceil projection of a detector row edge through the authenticated bottom crop.
// The overflow guards mirror the SM5 consumers, which have no uint64 arithmetic.
bool V2SubtitleOcrProjectRowCeil(
    uint source_width, uint source_height, uint field_width, uint field_height,
    uint detector_y, out uint projected_y) {
    projected_y = 0u;
    if (source_width == 0u || source_height == 0u || field_height == 0u ||
        detector_y > V2_OCR_OUTPUT_HEIGHT ||
        !V2SubtitleOcrFieldIsCalibrated(field_width, field_height)) return false;
    uint crop_quotient = source_width / V2_OCR_CROP_ASPECT_WIDTH;
    uint crop_remainder = source_width % V2_OCR_CROP_ASPECT_WIDTH;
    if (crop_quotient > 0xffffffffu / V2_OCR_CROP_ASPECT_HEIGHT ||
        crop_remainder > 0xffffffffu / V2_OCR_CROP_ASPECT_HEIGHT) return false;
    uint crop_height = min(
        source_height,
        crop_quotient * V2_OCR_CROP_ASPECT_HEIGHT +
        (crop_remainder * V2_OCR_CROP_ASPECT_HEIGHT +
         V2_OCR_CROP_ASPECT_WIDTH - 1u) / V2_OCR_CROP_ASPECT_WIDTH);
    uint crop_top = source_height - crop_height;
    if (source_height > 0xffffffffu / V2_OCR_OUTPUT_HEIGHT) return false;
    uint denominator = V2_OCR_OUTPUT_HEIGHT * source_height;
    if (denominator == 0u || denominator > 0xffffffffu / field_height) return false;
    uint source_y_numerator =
        crop_top * V2_OCR_OUTPUT_HEIGHT + detector_y * crop_height;
    uint scaled = source_y_numerator * field_height;
    projected_y = min(
        scaled / denominator + (scaled % denominator != 0u ? 1u : 0u),
        field_height);
    return true;
}

bool V2SubtitleOcrRibbonMinBottom(
    uint source_width, uint source_height, uint field_width, uint field_height,
    out uint minimum_bottom) {
    return V2SubtitleOcrProjectRowCeil(
        source_width, source_height, field_width, field_height,
        V2_OCR_SAFE_ROW_BOTTOM - V2_OCR_RIBBON_BOTTOM_TOLERANCE_PIXELS,
        minimum_bottom);
}

cbuffer DepthCoordinateV2Constants : register(b1) {
    float v2_raw_coordinate_scale;
    float v2_collapse_abs_epsilon;
    float v2_far_tau;
    float v2_near_log_tau;
    float v2_requested_gain;
    float v2_max_horizontal_slope;
    float v2_direct_container_limit;
    float v2_convergence_curve_default;
};

#define V2_CONSTANT_WORD_COUNT 8u
#define V2_CONSTANT_VECTOR_COUNT 2u
#define V2_FRAME_STATS_WORD_COUNT 8u
#define V2_FRAME_STATS_VECTOR_COUNT 2u

#define V2_FRAME_STATS_WORD_MEAN 0u
#define V2_FRAME_STATS_VECTOR_MEAN 0u
#define V2_FRAME_STATS_MEAN(value) ((value).x)
#define V2_FRAME_STATS_WORD_POPULATION_STD 1u
#define V2_FRAME_STATS_VECTOR_POPULATION_STD 0u
#define V2_FRAME_STATS_POPULATION_STD(value) ((value).y)
#define V2_FRAME_STATS_WORD_MINIMUM 2u
#define V2_FRAME_STATS_VECTOR_MINIMUM 0u
#define V2_FRAME_STATS_MINIMUM(value) ((value).z)
#define V2_FRAME_STATS_WORD_MAXIMUM 3u
#define V2_FRAME_STATS_VECTOR_MAXIMUM 0u
#define V2_FRAME_STATS_MAXIMUM(value) ((value).w)
#define V2_FRAME_STATS_WORD_VALID_COUNT 4u
#define V2_FRAME_STATS_VECTOR_VALID_COUNT 1u
#define V2_FRAME_STATS_VALID_COUNT(value) ((value).x)
#define V2_FRAME_STATS_WORD_TEXEL_COUNT 5u
#define V2_FRAME_STATS_VECTOR_TEXEL_COUNT 1u
#define V2_FRAME_STATS_TEXEL_COUNT(value) ((value).y)
#define V2_FRAME_STATS_WORD_VALID 6u
#define V2_FRAME_STATS_VECTOR_VALID 1u
#define V2_FRAME_STATS_VALID(value) ((value).z)
#define V2_FRAME_STATS_WORD_RESERVED 7u
#define V2_FRAME_STATS_VECTOR_RESERVED 1u
#define V2_FRAME_STATS_RESERVED(value) ((value).w)

#define V2_STATE_WORD_CENTER 0u
#define V2_STATE_VECTOR_CENTER 0u
#define V2_STATE_CENTER(value) ((value).x)
#define V2_STATE_WORD_INVERSE_SCALE 1u
#define V2_STATE_VECTOR_INVERSE_SCALE 0u
#define V2_STATE_INVERSE_SCALE(value) ((value).y)
#define V2_STATE_WORD_CONVERGENCE_CURVE 2u
#define V2_STATE_VECTOR_CONVERGENCE_CURVE 0u
#define V2_STATE_CONVERGENCE_CURVE(value) ((value).z)
#define V2_STATE_WORD_CONTAINER_SCALE 3u
#define V2_STATE_VECTOR_CONTAINER_SCALE 0u
#define V2_STATE_CONTAINER_SCALE(value) ((value).w)
#define V2_STATE_WORD_CALIBRATION_REVISION 4u
#define V2_STATE_VECTOR_CALIBRATION_REVISION 1u
#define V2_STATE_CALIBRATION_REVISION(value) ((value).x)
#define V2_STATE_WORD_FRAME_VALID 5u
#define V2_STATE_VECTOR_FRAME_VALID 1u
#define V2_STATE_FRAME_VALID(value) ((value).y)
#define V2_STATE_WORD_CONFIRMED_CUT_COUNT 6u
#define V2_STATE_VECTOR_CONFIRMED_CUT_COUNT 1u
#define V2_STATE_CONFIRMED_CUT_COUNT(value) ((value).z)
#define V2_STATE_WORD_CONTRACT_TAG_BITS 7u
#define V2_STATE_VECTOR_CONTRACT_TAG_BITS 1u
#define V2_STATE_CONTRACT_TAG_BITS(value) ((value).w)
#define V2_STATE_WORD_CAMERA_CENTER_INTEGRITY_BITS 8u
#define V2_STATE_VECTOR_CAMERA_CENTER_INTEGRITY_BITS 2u
#define V2_STATE_CAMERA_CENTER_INTEGRITY_BITS(value) ((value).x)
#define V2_STATE_WORD_RENDERER_AUTHORIZATION_BITS 9u
#define V2_STATE_VECTOR_RENDERER_AUTHORIZATION_BITS 2u
#define V2_STATE_RENDERER_AUTHORIZATION_BITS(value) ((value).y)
#define V2_STATE_WORD_MAPPING_STATE_RESERVED_1 10u
#define V2_STATE_VECTOR_MAPPING_STATE_RESERVED_1 2u
#define V2_STATE_MAPPING_STATE_RESERVED_1(value) ((value).z)
#define V2_STATE_WORD_MAPPING_STATE_RESERVED_2 11u
#define V2_STATE_VECTOR_MAPPING_STATE_RESERVED_2 2u
#define V2_STATE_MAPPING_STATE_RESERVED_2(value) ((value).w)

#endif
