// Generated by tools/sbsbench/generate_depth_coordinate_v2_contract.py.
// Edit tools/sbsbench/contracts/depth-coordinate-v2-v1.json instead.
#ifndef DEPTH_COORDINATE_V2_CONTRACT_GENERATED_HLSL
#define DEPTH_COORDINATE_V2_CONTRACT_GENERATED_HLSL

#define V2_CONTRACT_SCHEMA 15u
#define V2_CONTRACT_TAG 0x7ADF0988u
#define V2_SHADOW_STATE_WORD_COUNT 12u
#define V2_SHADOW_STATE_VECTOR_COUNT 3u
#define V2_DIRECT_CONTAINER_LIMIT 0.04f
#define V2_MAX_VERTICAL_SHEAR 2.0f
#define V2_VERTICAL_MAJORANT_SHARE 0.75f
static const float v2_max_vertical_shear = V2_MAX_VERTICAL_SHEAR;
static const float v2_vertical_majorant_share = V2_VERTICAL_MAJORANT_SHARE;

cbuffer DepthCoordinateV2Constants : register(b1) {
    float v2_raw_coordinate_scale;
    float v2_collapse_abs_epsilon;
    float v2_far_tau;
    float v2_near_log_tau;
    float v2_requested_gain;
    float v2_max_horizontal_slope;
    float v2_direct_container_limit;
    float v2_convergence_curve_default;
    float v2_near_tail_probe_u;
    float v2_near_tail_coverage_low;
    float v2_near_tail_coverage_high;
    float v2_near_log_tau_dense;
};

#define V2_CONSTANT_WORD_COUNT 12u
#define V2_CONSTANT_VECTOR_COUNT 3u
#define V2_FRAME_STATS_WORD_COUNT 8u
#define V2_FRAME_STATS_VECTOR_COUNT 2u

#define V2_FRAME_STATS_WORD_MEAN 0u
#define V2_FRAME_STATS_VECTOR_MEAN 0u
#define V2_FRAME_STATS_MEAN(value) ((value).x)
#define V2_FRAME_STATS_WORD_POPULATION_STD 1u
#define V2_FRAME_STATS_VECTOR_POPULATION_STD 0u
#define V2_FRAME_STATS_POPULATION_STD(value) ((value).y)
#define V2_FRAME_STATS_WORD_MINIMUM 2u
#define V2_FRAME_STATS_VECTOR_MINIMUM 0u
#define V2_FRAME_STATS_MINIMUM(value) ((value).z)
#define V2_FRAME_STATS_WORD_MAXIMUM 3u
#define V2_FRAME_STATS_VECTOR_MAXIMUM 0u
#define V2_FRAME_STATS_MAXIMUM(value) ((value).w)
#define V2_FRAME_STATS_WORD_VALID_COUNT 4u
#define V2_FRAME_STATS_VECTOR_VALID_COUNT 1u
#define V2_FRAME_STATS_VALID_COUNT(value) ((value).x)
#define V2_FRAME_STATS_WORD_TEXEL_COUNT 5u
#define V2_FRAME_STATS_VECTOR_TEXEL_COUNT 1u
#define V2_FRAME_STATS_TEXEL_COUNT(value) ((value).y)
#define V2_FRAME_STATS_WORD_VALID 6u
#define V2_FRAME_STATS_VECTOR_VALID 1u
#define V2_FRAME_STATS_VALID(value) ((value).z)
#define V2_FRAME_STATS_WORD_RESERVED 7u
#define V2_FRAME_STATS_VECTOR_RESERVED 1u
#define V2_FRAME_STATS_RESERVED(value) ((value).w)

#define V2_STATE_WORD_CENTER 0u
#define V2_STATE_VECTOR_CENTER 0u
#define V2_STATE_CENTER(value) ((value).x)
#define V2_STATE_WORD_INVERSE_SCALE 1u
#define V2_STATE_VECTOR_INVERSE_SCALE 0u
#define V2_STATE_INVERSE_SCALE(value) ((value).y)
#define V2_STATE_WORD_CONVERGENCE_CURVE 2u
#define V2_STATE_VECTOR_CONVERGENCE_CURVE 0u
#define V2_STATE_CONVERGENCE_CURVE(value) ((value).z)
#define V2_STATE_WORD_CONTAINER_SCALE 3u
#define V2_STATE_VECTOR_CONTAINER_SCALE 0u
#define V2_STATE_CONTAINER_SCALE(value) ((value).w)
#define V2_STATE_WORD_CALIBRATION_REVISION 4u
#define V2_STATE_VECTOR_CALIBRATION_REVISION 1u
#define V2_STATE_CALIBRATION_REVISION(value) ((value).x)
#define V2_STATE_WORD_FRAME_VALID 5u
#define V2_STATE_VECTOR_FRAME_VALID 1u
#define V2_STATE_FRAME_VALID(value) ((value).y)
#define V2_STATE_WORD_CONFIRMED_CUT_COUNT 6u
#define V2_STATE_VECTOR_CONFIRMED_CUT_COUNT 1u
#define V2_STATE_CONFIRMED_CUT_COUNT(value) ((value).z)
#define V2_STATE_WORD_CONTRACT_TAG_BITS 7u
#define V2_STATE_VECTOR_CONTRACT_TAG_BITS 1u
#define V2_STATE_CONTRACT_TAG_BITS(value) ((value).w)
#define V2_STATE_WORD_LATCHED_NEAR_TAIL_COVERAGE 8u
#define V2_STATE_VECTOR_LATCHED_NEAR_TAIL_COVERAGE 2u
#define V2_STATE_LATCHED_NEAR_TAIL_COVERAGE(value) ((value).x)
#define V2_STATE_WORD_EFFECTIVE_NEAR_LOG_TAU 9u
#define V2_STATE_VECTOR_EFFECTIVE_NEAR_LOG_TAU 2u
#define V2_STATE_EFFECTIVE_NEAR_LOG_TAU(value) ((value).y)
#define V2_STATE_WORD_LATCHED_NEAR_TAIL_COUNT 10u
#define V2_STATE_VECTOR_LATCHED_NEAR_TAIL_COUNT 2u
#define V2_STATE_LATCHED_NEAR_TAIL_COUNT(value) ((value).z)
#define V2_STATE_WORD_CAMERA_CENTER_INTEGRITY_BITS 11u
#define V2_STATE_VECTOR_CAMERA_CENTER_INTEGRITY_BITS 2u
#define V2_STATE_CAMERA_CENTER_INTEGRITY_BITS(value) ((value).w)

#endif
