#ifndef HOST_SBS_NEAR_IDENTICAL_HISTORY_OWNER_HLSL
#define HOST_SBS_NEAR_IDENTICAL_HISTORY_OWNER_HLSL

#define NEAR_IDENTICAL_HISTORY_OWNER_TAG 0x3142484Eu
#define NEAR_IDENTICAL_HISTORY_OWNER_SCHEMA 2u

#define NEAR_IDENTICAL_WORK_FLAGS_COOKIE 0x6F435257u
#define NEAR_IDENTICAL_WORK_OPTIONAL_OCR (1u << 0u)
#define NEAR_IDENTICAL_WORK_SUBTITLE_OBSERVATION (1u << 1u)
#define NEAR_IDENTICAL_WORK_OPTIONAL_OCR_DUE (1u << 3u)
#define NEAR_IDENTICAL_WORK_SUBTITLE_OBSERVATION_DUE (1u << 4u)

#define NEAR_IDENTICAL_HISTORY_WORD_CONTRACT_TAG 0u
#define NEAR_IDENTICAL_HISTORY_WORD_CONTRACT_SCHEMA 1u
#define NEAR_IDENTICAL_HISTORY_WORD_FRAME_LOW 2u
#define NEAR_IDENTICAL_HISTORY_WORD_FRAME_HIGH 3u
#define NEAR_IDENTICAL_HISTORY_WORD_DOMAIN_TAG_LOW 4u
#define NEAR_IDENTICAL_HISTORY_WORD_DOMAIN_TAG_HIGH 5u
#define NEAR_IDENTICAL_HISTORY_WORD_TARGET_WIDTH 6u
#define NEAR_IDENTICAL_HISTORY_WORD_TARGET_HEIGHT 7u
#define NEAR_IDENTICAL_HISTORY_WORD_OBSERVATION_TIMESTAMP_LOW 8u
#define NEAR_IDENTICAL_HISTORY_WORD_OBSERVATION_TIMESTAMP_HIGH 9u
#define NEAR_IDENTICAL_HISTORY_WORD_COUNT 10u

bool NearIdenticalWorkValid(uint flags) {
    return flags == 0u ||
        flags == NEAR_IDENTICAL_WORK_OPTIONAL_OCR ||
        flags == NEAR_IDENTICAL_WORK_SUBTITLE_OBSERVATION ||
        flags == NEAR_IDENTICAL_WORK_OPTIONAL_OCR_DUE ||
        flags == NEAR_IDENTICAL_WORK_SUBTITLE_OBSERVATION_DUE;
}

#endif
