/**
 * @file tests/unit/test_http_pairing.cpp
 * @brief Test src/nvhttp.cpp HTTP pairing process
 */

#include "../tests_common.h"

#include <atomic>
#include <src/nvhttp.h>
#include <src/rtsp.h>
#include <src/stream.h>
#include <thread>
#include <vector>

using namespace nvhttp;

struct pairing_input {
  std::shared_ptr<pair_session_t> session;
  /**
   * Normally server challenge is generated by the server, but for testing purposes
   * we can override it with a custom value. This way the process is deterministic.
   */
  std::string override_server_challenge;
  std::string pin;
  std::string client_challenge;
  std::string server_challenge_resp;
  std::string client_pairing_secret;
};

struct pairing_output {
  bool phase_1_success;
  bool phase_2_success;
  bool phase_3_success;
  bool phase_4_success;
};

const std::string PRIVATE_KEY = R"(-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDLePNlWN06FLlM
ujWzIX8UICO7SWfH5DXlafVjpxwi/WCkdO6FxixqRNGu71wMvJXFbDlNR8fqX2xo
+eq17J3uFKn+qdjmP3L38bkqxhoJ/nCrXkeGyCTQ+Daug63ZYSJeW2Mmf+LAR5/i
/fWYfXpSlbcf5XJQPEWvENpLqWu+NOU50dJXIEVYpUXRx2+x4ZbwkH7tVJm94L+C
OUyiJKQPyWgU2aFsyJGwHFfePfSUpfYHqbHZV/ILpY59VJairBwE99bx/mBvMI7a
hBmJTSDuDffJcPDhFF5kZa0UkQPrPvhXcQaSRti7v0VonEQj8pTSnGYr9ktWKk92
wxDyn9S3AgMBAAECggEAbEhQ14WELg2rUz7hpxPTaiV0fo4hEcrMN+u8sKzVF3Xa
QYsNCNoe9urq3/r39LtDxU3D7PGfXYYszmz50Jk8ruAGW8WN7XKkv3i/fxjv8JOc
6EYDMKJAnYkKqLLhCQddX/Oof2udg5BacVWPpvhX6a1NSEc2H6cDupfwZEWkVhMi
bCC3JcNmjFa8N7ow1/5VQiYVTjpxfV7GY1GRe7vMvBucdQKH3tUG5PYXKXytXw/j
KDLaECiYVT89KbApkI0zhy7I5g3LRq0Rs5fmYLCjVebbuAL1W5CJHFJeFOgMKvnO
QSl7MfHkTnzTzUqwkwXjgNMGsTosV4UloL9gXVF6GQKBgQD5fI771WETkpaKjWBe
6XUVSS98IOAPbTGpb8CIhSjzCuztNAJ+0ey1zklQHonMFbdmcWTkTJoF3ECqAos9
vxB4ROg+TdqGDcRrXa7Twtmhv66QvYxttkaK3CqoLX8CCTnjgXBCijo6sCpo6H1T
+y55bBDpxZjNFT5BV3+YPBfWQwKBgQDQyNt+saTqJqxGYV7zWQtOqKORRHAjaJpy
m5035pky5wORsaxQY8HxbsTIQp9jBSw3SQHLHN/NAXDl2k7VAw/axMc+lj9eW+3z
2Hv5LVgj37jnJYEpYwehvtR0B4jZnXLyLwShoBdRPkGlC5fs9+oWjQZoDwMLZfTg
eZVOJm6SfQKBgQDfxYcB/kuKIKsCLvhHaSJpKzF6JoqRi6FFlkScrsMh66TCxSmP
0n58O0Cqqhlyge/z5LVXyBVGOF2Pn6SAh4UgOr4MVAwyvNp2aprKuTQ2zhSnIjx4
k0sGdZ+VJOmMS/YuRwUHya+cwDHp0s3Gq77tja5F38PD/s/OD8sUIqJGvQKBgBfI
6ghy4GC0ayfRa+m5GSqq14dzDntaLU4lIDIAGS/NVYDBhunZk3yXq99Mh6/WJQVf
Uc77yRsnsN7ekeB+as33YONmZm2vd1oyLV1jpwjfMcdTZHV8jKAGh1l4ikSQRUoF
xTdMb5uXxg6xVWtvisFq63HrU+N2iAESmMnAYxRZAoGAVEFJRRjPrSIUTCCKRiTE
br+cHqy6S5iYRxGl9riKySBKeU16fqUACIvUqmqlx4Secj3/Hn/VzYEzkxcSPwGi
qMgdS0R+tacca7NopUYaaluneKYdS++DNlT/m+KVHqLynQr54z1qBlThg9KGrpmM
LGZkXtQpx6sX7v3Kq56PkNk=
-----END PRIVATE KEY-----)";
const std::string PUBLIC_CERT = R"(-----BEGIN CERTIFICATE-----
MIIC6zCCAdOgAwIBAgIBATANBgkqhkiG9w0BAQsFADA5MQswCQYDVQQGEwJJVDEW
MBQGA1UECgwNR2FtZXNPbldoYWxlczESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTIy
MDQwOTA5MTYwNVoXDTQyMDQwNDA5MTYwNVowOTELMAkGA1UEBhMCSVQxFjAUBgNV
BAoMDUdhbWVzT25XaGFsZXMxEjAQBgNVBAMMCWxvY2FsaG9zdDCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAMt482VY3ToUuUy6NbMhfxQgI7tJZ8fkNeVp
9WOnHCL9YKR07oXGLGpE0a7vXAy8lcVsOU1Hx+pfbGj56rXsne4Uqf6p2OY/cvfx
uSrGGgn+cKteR4bIJND4Nq6DrdlhIl5bYyZ/4sBHn+L99Zh9elKVtx/lclA8Ra8Q
2kupa7405TnR0lcgRVilRdHHb7HhlvCQfu1Umb3gv4I5TKIkpA/JaBTZoWzIkbAc
V9499JSl9gepsdlX8guljn1UlqKsHAT31vH+YG8wjtqEGYlNIO4N98lw8OEUXmRl
rRSRA+s++FdxBpJG2Lu/RWicRCPylNKcZiv2S1YqT3bDEPKf1LcCAwEAATANBgkq
hkiG9w0BAQsFAAOCAQEAqPBqzvDjl89pZMll3Ge8RS7HeDuzgocrhOcT2jnk4ag7
/TROZuISjDp6+SnL3gPEt7E2OcFAczTg3l/wbT5PFb6vM96saLm4EP0zmLfK1FnM
JDRahKutP9rx6RO5OHqsUB+b4jA4W0L9UnXUoLKbjig501AUix0p52FBxu+HJ90r
HlLs3Vo6nj4Z/PZXrzaz8dtQ/KJMpd/g/9xlo6BKAnRk5SI8KLhO4hW6zG0QA56j
X4wnh1bwdiidqpcgyuKossLOPxbS786WmsesaAWPnpoY6M8aija+ALwNNuWWmyMg
9SVDV76xJzM36Uq7Kg3QJYTlY04WmPIdJHkCtXWf9g==
-----END CERTIFICATE-----)";

const std::vector<std::string> &distinct_test_certificates() {
  static const auto certificates = []() {
    std::vector<std::string> result;
    result.reserve(8);
    for (int index = 0; index < 8; ++index) {
      result.push_back(crypto::gen_creds("pairing-client-" + std::to_string(index), 2048).x509);
    }
    return result;
  }();
  return certificates;
}

struct PairingTest: testing::TestWithParam<std::tuple<pairing_input, pairing_output>> {};

TEST_P(PairingTest, Run) {
  auto [input, expected] = GetParam();

  // GoogleTest retains parameter objects across --gtest_repeat runs. Treat the shared object as
  // an immutable seed and construct a fresh session so moved certificates, cipher state, and
  // phase progression can never leak from one invocation into the next.
  pair_session_t session;
  session.client.uniqueID = input.session->client.uniqueID;
  session.client.cert = input.session->client.cert;
  session.client.name = input.session->client.name;
  session.async_insert_pin.salt = input.session->async_insert_pin.salt;

  boost::property_tree::ptree tree;

  // Pairing now writes directly to the authoritative client store. Keep this unit test isolated
  // from any real/default state-file path while still exercising that production code path.
  const bool previous_fresh_state = config::sunshine.flags[config::flag::FRESH_STATE];
  config::sunshine.flags[config::flag::FRESH_STATE] = true;
  erase_all_clients();
  auto restore_fresh_state = util::fail_guard([&]() {
    erase_all_clients();
    config::sunshine.flags[config::flag::FRESH_STATE] = previous_fresh_state;
  });

  setup(PRIVATE_KEY, PUBLIC_CERT);

  // phase 1
  getservercert(session, tree, input.pin);
  ASSERT_EQ(tree.get<int>("root.paired") == 1, expected.phase_1_success);
  if (!expected.phase_1_success) {
    return;
  }

  // phase 2
  clientchallenge(session, tree, input.client_challenge);
  ASSERT_EQ(tree.get<int>("root.paired") == 1, expected.phase_2_success);
  if (!expected.phase_2_success) {
    return;
  }

  // phase 3
  serverchallengeresp(session, tree, input.server_challenge_resp);
  ASSERT_EQ(tree.get<int>("root.paired") == 1, expected.phase_3_success);
  if (!expected.phase_3_success) {
    return;
  }
  session.serverchallenge = input.override_server_challenge;

  // phase 4
  const auto clients_before = get_all_clients().size();
  clientpairingsecret(session, tree, input.client_pairing_secret);
  ASSERT_EQ(tree.get<int>("root.paired") == 1, expected.phase_4_success);

  // Check that the verified client was added to the authoritative paired-device store.
  if (expected.phase_4_success) {
    const auto clients = get_all_clients();
    ASSERT_EQ(clients.size(), clients_before + 1);
    ASSERT_EQ(clients.back().at("name").get<std::string>(), session.client.name);
    ASSERT_EQ(
      clients.back().at("perm").get<std::uint32_t>(),
      static_cast<std::uint32_t>(crypto::PERM::_all)
    );
    // FRESH_STATE suppresses persistence, not live authorization. The certificate must be in the
    // same in-memory chain used by the HTTPS verifier immediately after phase 4.
    ASSERT_TRUE(is_client_certificate_authorized(PUBLIC_CERT));
  }
}

INSTANTIATE_TEST_SUITE_P(
  TestWorkingPairing,
  PairingTest,
  testing::Values(
    std::make_tuple(
      pairing_input {
        .session = std::make_shared<pair_session_t>(
          pair_session_t {
            .client = {
              .uniqueID = "1234",
              .cert = PUBLIC_CERT,
              .name = "test"
            },
            .async_insert_pin = {.salt = "ff5dc6eda99339a8a0793e216c4257c4"}
          }
        ),
        .override_server_challenge = util::from_hex_vec("AAAAAAAAAAAAAAAA", true),
        .pin = "5338",
        /* AES("CLIENT CHALLENGE") */
        .client_challenge = util::from_hex_vec("741CD3D6890C16DA39D53BCA0893AAF0", true),
        /* SHA = SHA265(server_challenge + public cert signature + "SECRET  ") = "6493DAE49C913E1AEAF37C1072F71D664B72B2C4DA1FFB4720BECE0D929E008A"
         * AES( SHA ) */
        .server_challenge_resp = util::from_hex_vec("920BABAE9F7599AA1CA8EC87FB3454C91872A7D8D5127DDC176C2FDAE635CF7A", true),
        /* secret + x509 signature */
        .client_pairing_secret = util::from_hex_vec("000102030405060708090A0B0C0D0EFF"  // secret
                                                    "9BB74D8DE2FF006C3F47FC45EFDAA97D433783AFAB3ACD85CA7ED2330BB2A7BD18A5B044AF8CAC177116FAE8A6E8E44653A8944A0F8EA138B2E013756D847D2C4FC52F736E2E7E9B4154712B18F8307B2A161E010F0587744163E42ECA9EA548FC435756EDCF1FEB94037631ABB72B29DDAC0EA5E61F2DBFCC3B20AA021473CC85AC98D88052CA6618ED1701EFBF142C18D5E779A3155B84DF65057D4823EC194E6DF14006793E8D7A3DCCE20A911636C4E01ECA8B54B9DE9F256F15DE9A980EA024B30D77579140D45EC220C738164BDEEEBF7364AE94A5FF9B784B40F2E640CE8603017DEEAC7B2AD77B807C643B7B349C110FE15F94C7B3D37FF15FDFBE26",
                                                    true)
      },
      pairing_output {true, true, true, true}
    ),
    // Testing that when passing some empty values we aren't triggering any exception
    std::make_tuple(pairing_input {
                      .session = std::make_shared<pair_session_t>(pair_session_t {.client = {}, .async_insert_pin = {.salt = "ff5dc6eda99339a8a0793e216c4257c4"}}),
                      .override_server_challenge = {},
                      .pin = {},
                      .client_challenge = {},
                      .server_challenge_resp = {},
                      .client_pairing_secret = util::from_hex_vec("000102030405060708090A0B0C0D0EFFxDEADBEEF", true),
                    },
                    // Only phase 4 will fail, when we check what has been exchanged
                    pairing_output {true, true, true, false}),
    // Testing that when passing some empty values we aren't triggering any exception
    std::make_tuple(pairing_input {
                      .session = std::make_shared<pair_session_t>(pair_session_t {.client = {.cert = PUBLIC_CERT}, .async_insert_pin = {.salt = "ff5dc6eda99339a8a0793e216c4257c4"}}),
                      .override_server_challenge = {},
                      .pin = {},
                      .client_challenge = {},
                      .server_challenge_resp = {},
                      .client_pairing_secret = util::from_hex_vec("000102030405060708090A0B0C0D0EFFxDEADBEEF", true),
                    },
                    // Only phase 4 will fail, when we check what has been exchanged
                    pairing_output {true, true, true, false})
  )
);

INSTANTIATE_TEST_SUITE_P(
  TestFailingPairing,
  PairingTest,
  testing::Values(
    /**
     * Wrong PIN
     */
    std::make_tuple(
      pairing_input {
        .session = std::make_shared<pair_session_t>(
          pair_session_t {
            .client = {
              .uniqueID = "1234",
              .cert = PUBLIC_CERT,
              .name = "test"
            },
            .async_insert_pin = {.salt = "ff5dc6eda99339a8a0793e216c4257c4"}
          }
        ),
        .override_server_challenge = util::from_hex_vec("AAAAAAAAAAAAAAAA", true),
        .pin = "0000",
        .client_challenge = util::from_hex_vec("741CD3D6890C16DA39D53BCA0893AAF0", true),
        .server_challenge_resp = util::from_hex_vec("920BABAE9F7599AA1CA8EC87FB3454C91872A7D8D5127DDC176C2FDAE635CF7A", true),
        .client_pairing_secret = util::from_hex_vec("000102030405060708090A0B0C0D0EFF"  // secret
                                                    "9BB74D8DE2FF006C3F47FC45EFDAA97D433783AFAB3ACD85CA7ED2330BB2A7BD18A5B044AF8CAC177116FAE8A6E8E44653A8944A0F8EA138B2E013756D847D2C4FC52F736E2E7E9B4154712B18F8307B2A161E010F0587744163E42ECA9EA548FC435756EDCF1FEB94037631ABB72B29DDAC0EA5E61F2DBFCC3B20AA021473CC85AC98D88052CA6618ED1701EFBF142C18D5E779A3155B84DF65057D4823EC194E6DF14006793E8D7A3DCCE20A911636C4E01ECA8B54B9DE9F256F15DE9A980EA024B30D77579140D45EC220C738164BDEEEBF7364AE94A5FF9B784B40F2E640CE8603017DEEAC7B2AD77B807C643B7B349C110FE15F94C7B3D37FF15FDFBE26",
                                                    true)
      },
      pairing_output {true, true, true, false}
    ),
    /**
     * Wrong client challenge
     */
    std::make_tuple(pairing_input {.session = std::make_shared<pair_session_t>(pair_session_t {.client = {.uniqueID = "1234", .cert = PUBLIC_CERT, .name = "test"}, .async_insert_pin = {.salt = "ff5dc6eda99339a8a0793e216c4257c4"}}), .override_server_challenge = util::from_hex_vec("AAAAAAAAAAAAAAAA", true), .pin = "5338", .client_challenge = util::from_hex_vec("741CD3D6890C16DA39D53BCA0893AAF0", true), .server_challenge_resp = util::from_hex_vec("WRONG", true),
                                   .client_pairing_secret = util::from_hex_vec("000102030405060708090A0B0C0D0EFF"  // secret
                                                                               "9BB74D8DE2FF006C3F47FC45EFDAA97D433783AFAB3ACD85CA7ED2330BB2A7BD18A5B044AF8CAC177116FAE8A6E8E44653A8944A0F8EA138B2E013756D847D2C4FC52F736E2E7E9B4154712B18F8307B2A161E010F0587744163E42ECA9EA548FC435756EDCF1FEB94037631ABB72B29DDAC0EA5E61F2DBFCC3B20AA021473CC85AC98D88052CA6618ED1701EFBF142C18D5E779A3155B84DF65057D4823EC194E6DF14006793E8D7A3DCCE20A911636C4E01ECA8B54B9DE9F256F15DE9A980EA024B30D77579140D45EC220C738164BDEEEBF7364AE94A5FF9B784B40F2E640CE8603017DEEAC7B2AD77B807C643B7B349C110FE15F94C7B3D37FF15FDFBE26",
                                                                               true)},
                    pairing_output {true, true, true, false}),
    /**
     * Wrong signature
     */
    std::make_tuple(pairing_input {.session = std::make_shared<pair_session_t>(pair_session_t {.client = {.uniqueID = "1234", .cert = PUBLIC_CERT, .name = "test"}, .async_insert_pin = {.salt = "ff5dc6eda99339a8a0793e216c4257c4"}}), .override_server_challenge = util::from_hex_vec("AAAAAAAAAAAAAAAA", true), .pin = "5338", .client_challenge = util::from_hex_vec("741CD3D6890C16DA39D53BCA0893AAF0", true), .server_challenge_resp = util::from_hex_vec("920BABAE9F7599AA1CA8EC87FB3454C91872A7D8D5127DDC176C2FDAE635CF7A", true),
                                   .client_pairing_secret = util::from_hex_vec("000102030405060708090A0B0C0D0EFF"  // secret
                                                                               "NOSIGNATURE",  // Wrong signature
                                                                               true)},
                    pairing_output {true, true, true, false}),
    /**
     * null values (phase 1)
     */
    std::make_tuple(pairing_input {.session = std::make_shared<pair_session_t>()}, pairing_output {false}),
    /**
     * null values (phase 4, phase 2 and 3 have no reason to fail since we are running them in order)
     */
    std::make_tuple(pairing_input {.session = std::make_shared<pair_session_t>(pair_session_t {.async_insert_pin = {.salt = "ff5dc6eda99339a8a0793e216c4257c4"}})}, pairing_output {true, true, true, false})
  )
);

TEST(PairingTest, OutOfOrderCalls) {
  boost::property_tree::ptree tree;

  setup(PRIVATE_KEY, PUBLIC_CERT);

  pair_session_t sess {};

  clientchallenge(sess, tree, "test");
  ASSERT_FALSE(tree.get<int>("root.paired") == 1);

  serverchallengeresp(sess, tree, "test");
  ASSERT_FALSE(tree.get<int>("root.paired") == 1);

  clientpairingsecret(sess, tree, "test");
  ASSERT_FALSE(tree.get<int>("root.paired") == 1);

  // This should work, it's the first time we call it
  sess.async_insert_pin.salt = "ff5dc6eda99339a8a0793e216c4257c4";
  getservercert(sess, tree, "test");
  ASSERT_TRUE(tree.get<int>("root.paired") == 1);

  // Calling it again should fail
  getservercert(sess, tree, "test");
  ASSERT_FALSE(tree.get<int>("root.paired") == 1);
}

TEST(PairingStateTest, ConcurrentFirstClientGrantIsAtomic) {
  const bool previous_fresh_state = config::sunshine.flags[config::flag::FRESH_STATE];
  config::sunshine.flags[config::flag::FRESH_STATE] = true;
  erase_all_clients();
  auto cleanup = util::fail_guard([&]() {
    erase_all_clients();
    config::sunshine.flags[config::flag::FRESH_STATE] = previous_fresh_state;
  });

  constexpr int client_count = 8;
  const auto &certificates = distinct_test_certificates();
  std::vector<std::jthread> clients;
  clients.reserve(client_count);
  for (int index = 0; index < client_count; ++index) {
    clients.emplace_back([index, &certificates]() {
      add_authorized_client_for_test("concurrent-" + std::to_string(index), certificates[index]);
    });
  }
  clients.clear();  // jthread destruction joins every insertion.

  const auto authorized = get_all_clients();
  ASSERT_EQ(authorized.size(), client_count);
  int full_control_clients = 0;
  int default_clients = 0;
  for (const auto &client : authorized) {
    const auto permission = client.at("perm").get<std::uint32_t>();
    full_control_clients += permission == static_cast<std::uint32_t>(crypto::PERM::_all);
    default_clients += permission == static_cast<std::uint32_t>(crypto::PERM::_default);
  }
  ASSERT_EQ(full_control_clients, 1);
  ASSERT_EQ(default_clients, client_count - 1);
  for (const auto &certificate : certificates) {
    ASSERT_TRUE(is_client_certificate_authorized(certificate));
  }
}

TEST(PairingStateTest, DuplicateCertificatePairingIsIdempotent) {
  const bool previous_fresh_state = config::sunshine.flags[config::flag::FRESH_STATE];
  config::sunshine.flags[config::flag::FRESH_STATE] = true;
  erase_all_clients();
  auto cleanup = util::fail_guard([&]() {
    erase_all_clients();
    config::sunshine.flags[config::flag::FRESH_STATE] = previous_fresh_state;
  });

  add_authorized_client_for_test("first-name", PUBLIC_CERT);
  const auto original = get_all_clients();
  ASSERT_EQ(original.size(), 1);

  // The same X.509 identity with different PEM whitespace is still the same client. Re-pairing
  // preserves the original UUID, name, permissions, and administrator settings.
  add_authorized_client_for_test("second-name", PUBLIC_CERT + "\n");
  const auto after_repair = get_all_clients();
  ASSERT_EQ(after_repair.size(), 1);
  EXPECT_EQ(after_repair.front(), original.front());
}

TEST(PairingStateTest, KeepAliveAuthorizationRefreshesAfterUpdateAndRevoke) {
  const bool previous_fresh_state = config::sunshine.flags[config::flag::FRESH_STATE];
  config::sunshine.flags[config::flag::FRESH_STATE] = true;
  erase_all_clients();
  auto cleanup = util::fail_guard([&]() {
    erase_all_clients();
    config::sunshine.flags[config::flag::FRESH_STATE] = previous_fresh_state;
  });

  add_authorized_client_for_test("before-update", PUBLIC_CERT);
  auto stale = get_authorized_client_for_test(PUBLIC_CERT);
  ASSERT_TRUE(stale);
  ASSERT_EQ(stale->perm, crypto::PERM::_all);

  ASSERT_TRUE(update_device_info(
    stale->uuid,
    "after-update",
    crypto::PERM::_no
  ));
  auto refreshed = refresh_authorized_client_for_test(stale);
  ASSERT_TRUE(refreshed);
  EXPECT_NE(refreshed.get(), stale.get());
  EXPECT_EQ(refreshed->name, "after-update");
  EXPECT_EQ(refreshed->perm, crypto::PERM::_no);

  ASSERT_TRUE(unpair_client(stale->uuid));
  EXPECT_FALSE(refresh_authorized_client_for_test(stale));
}

namespace {
  std::shared_ptr<stream::session_t> make_test_stream_session(
    std::uint32_t id,
    std::string uuid,
    std::string name,
    crypto::PERM permissions
  ) {
    stream::config_t stream_config {};
    rtsp_stream::launch_session_t launch_session {};
    launch_session.id = id;
    launch_session.unique_id = std::move(uuid);
    launch_session.device_name = std::move(name);
    launch_session.perm = permissions;
    launch_session.gcm_key.resize(16);
    launch_session.iv.resize(16);
    return stream::session::alloc(stream_config, launch_session);
  }
}  // namespace

TEST(PairingStateTest, UpdatesActiveSessionAndRejectsASecondSession) {
  const bool previous_fresh_state = config::sunshine.flags[config::flag::FRESH_STATE];
  config::sunshine.flags[config::flag::FRESH_STATE] = true;
  erase_all_clients();
  auto state_cleanup = util::fail_guard([&]() {
    erase_all_clients();
    config::sunshine.flags[config::flag::FRESH_STATE] = previous_fresh_state;
  });

  add_authorized_client_for_test("single-session", PUBLIC_CERT);
  const auto client = get_authorized_client_for_test(PUBLIC_CERT);
  ASSERT_TRUE(client);

  auto first = make_test_stream_session(1, client->uuid, "before", crypto::PERM::_default);
  auto second = make_test_stream_session(2, client->uuid, "before", crypto::PERM::_default);
  auto unrelated = make_test_stream_session(3, "unrelated", "other", crypto::PERM::_default);
  auto session_cleanup = util::fail_guard([&]() {
    rtsp_stream::remove_session_for_test(first);
  });
  ASSERT_TRUE(rtsp_stream::insert_session_for_test(first));
  EXPECT_FALSE(rtsp_stream::insert_session_for_test(second));
  EXPECT_FALSE(rtsp_stream::insert_session_for_test(unrelated));

  EXPECT_EQ(rtsp_stream::find_session(client->uuid), first);
  ASSERT_TRUE(rtsp_stream::active_session_uuid());
  EXPECT_EQ(*rtsp_stream::active_session_uuid(), client->uuid);
  ASSERT_TRUE(update_device_info(
    client->uuid,
    "after",
    crypto::PERM::_all
  ));

  EXPECT_EQ(stream::session::permissions(*first), crypto::PERM::_all);
  EXPECT_EQ(stream::session::client_name(*first), "after");
  EXPECT_EQ(stream::session::permissions(*second), crypto::PERM::_default);
  EXPECT_EQ(stream::session::client_name(*second), "before");
  EXPECT_EQ(stream::session::permissions(*unrelated), crypto::PERM::_default);
  EXPECT_EQ(stream::session::client_name(*unrelated), "other");

  // A launch authenticated before the update but inserted afterward must receive the latest
  // policy rather than the stale permission snapshot carried by its RTSP launch record.
  rtsp_stream::remove_session_for_test(first);
  auto late = make_test_stream_session(4, client->uuid, "stale", crypto::PERM::_default);
  ASSERT_TRUE(rtsp_stream::insert_session_for_test(late));
  auto late_cleanup = util::fail_guard([&]() {
    rtsp_stream::remove_session_for_test(late);
  });
  EXPECT_EQ(stream::session::permissions(*late), crypto::PERM::_all);
  EXPECT_EQ(stream::session::client_name(*late), "after");
}

TEST(PairingStateTest, RevokingViewStopsActiveSessionAndRejectsLateLaunch) {
  const bool previous_fresh_state = config::sunshine.flags[config::flag::FRESH_STATE];
  config::sunshine.flags[config::flag::FRESH_STATE] = true;
  erase_all_clients();
  auto state_cleanup = util::fail_guard([&]() {
    erase_all_clients();
    config::sunshine.flags[config::flag::FRESH_STATE] = previous_fresh_state;
  });

  add_authorized_client_for_test("revoked-client", PUBLIC_CERT);
  const auto client = get_authorized_client_for_test(PUBLIC_CERT);
  ASSERT_TRUE(client);

  auto first = make_test_stream_session(10, client->uuid, "before", crypto::PERM::_default);
  auto session_cleanup = util::fail_guard([&]() {
    rtsp_stream::remove_session_for_test(first);
  });
  ASSERT_TRUE(rtsp_stream::insert_session_for_test(first));

  stream::session::set_state_for_test(*first, stream::session::state_e::RUNNING);

  ASSERT_TRUE(update_device_info(
    client->uuid,
    "revoked-client",
    crypto::PERM::_no
  ));

  EXPECT_EQ(stream::session::state(*first), stream::session::state_e::STOPPING);
  EXPECT_EQ(stream::session::permissions(*first), crypto::PERM::_no);

  rtsp_stream::remove_session_for_test(first);
  auto late = make_test_stream_session(13, client->uuid, "stale", crypto::PERM::_all);
  EXPECT_FALSE(rtsp_stream::insert_session_for_test(late));
}

TEST(PairingStateTest, UnpairStopsActiveSessionAndRejectsLateLaunch) {
  const bool previous_fresh_state = config::sunshine.flags[config::flag::FRESH_STATE];
  config::sunshine.flags[config::flag::FRESH_STATE] = true;
  erase_all_clients();
  auto state_cleanup = util::fail_guard([&]() {
    erase_all_clients();
    config::sunshine.flags[config::flag::FRESH_STATE] = previous_fresh_state;
  });

  add_authorized_client_for_test("unpaired-client", PUBLIC_CERT);
  const auto client = get_authorized_client_for_test(PUBLIC_CERT);
  ASSERT_TRUE(client);

  auto first = make_test_stream_session(20, client->uuid, "before", crypto::PERM::_default);
  auto session_cleanup = util::fail_guard([&]() {
    rtsp_stream::remove_session_for_test(first);
  });
  ASSERT_TRUE(rtsp_stream::insert_session_for_test(first));

  stream::session::set_state_for_test(*first, stream::session::state_e::RUNNING);

  ASSERT_TRUE(unpair_client(client->uuid));
  EXPECT_EQ(stream::session::state(*first), stream::session::state_e::STOPPING);

  rtsp_stream::remove_session_for_test(first);
  auto late = make_test_stream_session(23, client->uuid, "stale", crypto::PERM::_all);
  EXPECT_FALSE(rtsp_stream::insert_session_for_test(late));
}

TEST(PairingStateTest, OlderRuntimePolicyCannotOverwriteNewerGeneration) {
  static std::atomic<std::uint64_t> next_generation {0};
  const auto newer_generation = next_generation.fetch_add(2, std::memory_order_relaxed) + 2;
  auto session = make_test_stream_session(
    30,
    "policy-generation-order",
    "initial",
    crypto::PERM::_default
  );
  auto cleanup = util::fail_guard([&]() {
    rtsp_stream::remove_session_for_test(session);
  });
  ASSERT_TRUE(rtsp_stream::insert_session_for_test(session));

  ASSERT_TRUE(rtsp_stream::publish_client_policy("policy-generation-order", newer_generation, "newer", crypto::PERM::_all, false));
  EXPECT_FALSE(rtsp_stream::publish_client_policy("policy-generation-order", newer_generation - 1, "older", crypto::PERM::_default, false));

  EXPECT_EQ(stream::session::permissions(*session), crypto::PERM::_all);
  EXPECT_EQ(stream::session::client_name(*session), "newer");
}

TEST(PairingStateTest, SessionWithoutViewPermissionIsRejectedWithoutRuntimeOverlay) {
  auto session = make_test_stream_session(
    31,
    "no-runtime-policy",
    "no-view",
    crypto::PERM::_no
  );
  EXPECT_FALSE(rtsp_stream::insert_session_for_test(session));
}

TEST(PairingStateTest, SessionRejectsDelayedOlderRuntimePolicy) {
  auto session = make_test_stream_session(
    32,
    "per-session-generation-order",
    "initial",
    crypto::PERM::_default
  );

  EXPECT_EQ(
    stream::session::update_client_policy(*session, 2, "newer", crypto::PERM::_all, false),
    stream::session::client_policy_result_e::updated
  );
  EXPECT_EQ(
    stream::session::update_client_policy(*session, 1, "older", crypto::PERM::_default, false),
    stream::session::client_policy_result_e::ignored
  );
  EXPECT_EQ(stream::session::permissions(*session), crypto::PERM::_all);
  EXPECT_EQ(stream::session::client_name(*session), "newer");
}

TEST(PairingStateTest, DelayedRevokeCannotStopSessionAfterNewerAllowPolicy) {
  static std::atomic<std::uint64_t> next_generation {0};
  const auto allow_generation = next_generation.fetch_add(2, std::memory_order_relaxed) + 2;
  const auto revoke_generation = allow_generation - 1;
  auto session = make_test_stream_session(
    33,
    "deferred-stop-generation-order",
    "initial",
    crypto::PERM::_all
  );
  auto cleanup = util::fail_guard([&]() {
    rtsp_stream::remove_session_for_test(session);
  });
  ASSERT_TRUE(rtsp_stream::insert_session_for_test(session));
  stream::session::set_state_for_test(*session, stream::session::state_e::RUNNING);

  auto delayed_revoke = rtsp_stream::stage_client_policy(
    "deferred-stop-generation-order",
    revoke_generation,
    "revoked",
    crypto::PERM::_no,
    true
  );
  ASSERT_TRUE(delayed_revoke.accepted);
  auto newer_allow = rtsp_stream::stage_client_policy(
    "deferred-stop-generation-order",
    allow_generation,
    "allowed",
    crypto::PERM::_all,
    false
  );
  ASSERT_TRUE(newer_allow.accepted);

  rtsp_stream::complete_client_policy(std::move(delayed_revoke));
  rtsp_stream::complete_client_policy(std::move(newer_allow));
  EXPECT_EQ(stream::session::state(*session), stream::session::state_e::RUNNING);
  EXPECT_EQ(stream::session::permissions(*session), crypto::PERM::_all);
  EXPECT_EQ(stream::session::client_name(*session), "allowed");
}

TEST(PairingStateTest, InvalidOtpAuthenticationDoesNotConsumeOtp) {
  constexpr std::string_view passphrase = "test-passphrase";
  constexpr std::string_view salt = "test-salt";
  const auto pin = request_otp(std::string(passphrase), "otp-client");
  ASSERT_FALSE(pin.empty());

  EXPECT_FALSE(authenticate_otp_for_test("invalid-authentication", std::string(salt)));

  const auto digest = util::hex(crypto::hash(pin + std::string(salt) + std::string(passphrase)), true);
  EXPECT_TRUE(authenticate_otp_for_test(std::string(digest.to_string_view()), std::string(salt)));
  EXPECT_FALSE(authenticate_otp_for_test(std::string(digest.to_string_view()), std::string(salt)));
}

TEST(PairingStateTest, BoundsUnauthenticatedPairingAndSerializesManualPin) {
  using admission = nvhttp::detail::pairing_admission_e;
  using nvhttp::detail::pairing_admission;

  EXPECT_EQ(pairing_admission(15, 16, false, false, false), admission::allowed);
  EXPECT_EQ(pairing_admission(16, 16, false, false, false), admission::capacity_reached);
  EXPECT_EQ(pairing_admission(16, 16, true, false, false), admission::allowed);
  EXPECT_EQ(pairing_admission(1, 16, false, true, true), admission::manual_pin_conflict);
  EXPECT_EQ(pairing_admission(1, 16, false, false, true), admission::allowed);
}
